exclude: [Gemfile, Gemfile.lock]
baseurl: "/new"
excerpt_separator: <!--more-->
root_breadcrumb: "/~Fort Royal"

collections:
  albums:
    output: false
  announces:
    output: false
  concerts:
    output: true
    permalink: /concerts/:path.html
  news:
    output: false
  songs:
    output: true
    permalink: /music/:path.html

defaults:
  -
    scope:
      path: ""
    values:
      layout: "default"
  -
    scope:
      path: ""
      type: concerts
    values:
      section_breadcrumb: "/concerts/~Концерты"
  -
    scope:
      path: ""
      type: songs
    values:
      section_breadcrumb: "/music/~Музыка"
